use std::{
    fs::File,
    io::{BufRead, BufReader},
    path::Path,
};

use colored::Colorize;

use anyhow::{Context, Result};

pub fn init_env() -> Result<()> {
    let exists = Path::new(".env.example").exists();

    if exists {
        println!("{}", "file exists, overwrite? (y/n) ");

        let mut input = String::new();
        std::io::stdin()
            .read_line(&mut input)
            .context("Failed to read user input")?;

        if input.trim().to_lowercase() != "y" {
            return Ok(());
        }
    }

    let file = File::open(".env").context("Could not find .env file")?;
    let reader = BufReader::new(file);

    let mut content: String = String::from("# GuardStack autogenerated .env.example\n");

    for line in reader.lines() {
        let line = line.context("Failed to read line from .env")?;
        if line.trim().is_empty() {
            continue;
        }
        if line.trim().starts_with('#') {
            content.push_str(&format!("\n{}", line));
            continue;
        }

        match line.trim().split_once('=') {
            Some((key, _)) => {
                content.push_str(&format!("\n{}=", key.trim()));
            }
            None => {
                println!(
                    "{}",
                    format!("⚠️  '{}' is malformed - skipping", line.trim()).yellow()
                );
            }
        }
    }

    std::fs::write(".env.example", content).context("Could not write content to .env.example")?;
    println!("✅ .env.example generated successfully!");
    Ok(())
}
